service: swiftcloud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  api:
    handler: dist/app.handler
    events:
    - httpApi:
        path: /
        method: ANY
    - httpApi:
        path: /{any+}
        method: ANY